import cx_Oracle

# Oracle 데이터베이스에 접속
conn = cx_Oracle.connect('hr/hr@localhost/xe')
print("Connected to Oracle Database")

# board 테이블 생성
cur = conn.cursor()
cur.execute('DROP TABLE board')
cur.execute('CREATE TABLE board (id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, title VARCHAR2(100), content VARCHAR2(4000), created_at DATE DEFAULT SYSDATE, updated_at DATE DEFAULT SYSDATE)')
print("board table created")

# 테이블 생성 후 커서와 연결 종료
cur.close()
conn.close()